# Generated by Django 4.2.14 on 2024-10-17 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('payment_per_hour', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight_carried', models.DecimalField(decimal_places=3, max_digits=5)),
                ('distance_driven', models.DecimalField(decimal_places=2, max_digits=5)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('truck_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='truck.truck')),
            ],
        ),
    ]
