# Generated by Django 4.2.14 on 2024-10-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
        ('shift', '0002_alter_shift_driver_name_alter_shift_truck_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='truck_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='truck.truck'),
        ),
    ]
