# Generated by Django 4.2.14 on 2024-10-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shift', '0003_alter_shift_truck_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_brand', to=settings.AUTH_USER_MODEL),
        ),
    ]
