# Generated by Django 4.2.14 on 2024-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_alter_shift_driver_name_alter_shift_truck_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='driver_name',
            new_name='driver_id',
        ),
    ]
