# Generated by Django 4.2.14 on 2024-10-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_brand', models.CharField(max_length=20)),
                ('truck_model', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
            ],
        ),
    ]
